### PR TITLE
Allow to be built without hybris/android/papi support

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Comment by peat-psuwit** [comment]
You may want to match the existing coding style for fallback with the other part of the code, but otherwise LGTM.

**Review by peat-psuwit — COMMENTED** [review]
It might worth try compiling without hybris support once to make sure they're proper.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This does not build if `-DREPOWERD_ENABLE_HYBRIS=OFF` is specified in the cmake invokation:

```
$ make -j1
[  4%] Built target GMock
[  9%] Built target suspend
[ 13%] Built target repowerd-core
[ 33%] Built target repowerd-adapters
[ 33%] Building CXX object src/CMakeFiles/repowerd-default-daemon-config.dir/default_daemon_config.cpp.o
/home/ubuntu/repowerd/src/default_daemon_config.cpp:85:36: error: invalid use of incomplete type ‘class repowerd::LightSensor’
 struct NullLightSensor : repowerd::LightSensor
                                    ^
In file included from /home/ubuntu/repowerd/src/default_daemon_config.cpp:19:0:
/home/ubuntu/repowerd/src/default_daemon_config.h:33:7: note: forward declaration of ‘class repowerd::LightSensor’
 class LightSensor;
       ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:88:19: error: ‘repowerd::LightHandler’ has not been declared
         repowerd::LightHandler const&) override
                   ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:87:35: error: ‘repowerd::HandlerRegistration {anonymous}::NullLightSensor::register_light_handler(const int&)’ marked ‘override’, but does not override
     repowerd::HandlerRegistration register_light_handler(
                                   ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:93:10: error: ‘void {anonymous}::NullLightSensor::enable_light_events()’ marked ‘override’, but does not override
     void enable_light_events() override {}
          ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:94:10: error: ‘void {anonymous}::NullLightSensor::disable_light_events()’ marked ‘override’, but does not override
     void disable_light_events() override {}
          ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:109:40: error: invalid use of incomplete type ‘class repowerd::ProximitySensor’
 struct NullProximitySensor : repowerd::ProximitySensor
                                        ^
In file included from /home/ubuntu/repowerd/src/default_daemon_config.h:21:0,
                 from /home/ubuntu/repowerd/src/default_daemon_config.cpp:19:
/home/ubuntu/repowerd/src/core/daemon_config.h:41:7: note: forward declaration of ‘class repowerd::ProximitySensor’
 class ProximitySensor;
       ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:112:19: error: ‘repowerd::ProximityHandler’ has not been declared
         repowerd::ProximityHandler const&) override
                   ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:116:15: error: ‘ProximityState’ in namespace ‘repowerd’ does not name a type
     repowerd::ProximityState proximity_state() override
               ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:111:35: error: ‘repowerd::HandlerRegistration {anonymous}::NullProximitySensor::register_proximity_handler(const int&)’ marked ‘override’, but does not override
     repowerd::HandlerRegistration register_proximity_handler(
                                   ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:120:10: error: ‘void {anonymous}::NullProximitySensor::enable_proximity_events()’ marked ‘override’, but does not override
     void enable_proximity_events() override {}
          ^
/home/ubuntu/repowerd/src/default_daemon_config.cpp:121:10: error: ‘void {anonymous}::NullProximitySensor::disable_proximity_events()’ marked ‘override’, but does not override
     void disable_proximity_events() override {}
          ^
In file included from /usr/include/c++/5/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/5/memory:82,
                 from /home/ubuntu/repowerd/src/core/daemon_config.h:21,
                 from /home/ubuntu/repowerd/src/default_daemon_config.h:21,
                 from /home/ubuntu/repowerd/src/default_daemon_config.cpp:19:
/usr/include/c++/5/bits/shared_ptr_base.h: In instantiation of ‘std::__shared_ptr<_Tp, _Lp>& std::__shared_ptr<_Tp, _Lp>::operator=(std::__shared_ptr<_Tp1, _Lp>&&) [with _Tp1 = {anonymous}::NullProximitySensor; _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’:
/usr/include/c++/5/bits/shared_ptr.h:302:4:   required from ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp1>&&) [with _Tp1 = {anonymous}::NullProximitySensor; _Tp = repowerd::ProximitySensor]’
/home/ubuntu/repowerd/src/default_daemon_config.cpp:283:22:   required from here
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: error: no matching function for call to ‘std::__shared_ptr<repowerd::ProximitySensor, (__gnu_cxx::_Lock_policy)2u>::__shared_ptr(std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type)’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:1146:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp, _Lp>&, std::nothrow_t) [with _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __weak_ptr<_Tp, _Lp>& __r, std::nothrow_t)
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:1146:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/5/bits/shared_ptr_base.h:1094:2: note: candidate: template<class _Alloc, class ... _Args> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...)
  __shared_ptr(_Sp_make_shared_tag __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:1094:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::_Sp_make_shared_tag’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:976:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t) [with _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u; std::nullptr_t = std::nullptr_t]
       constexpr __shared_ptr(nullptr_t) noexcept : __shared_ptr() { }
                 ^
/usr/include/c++/5/bits/shared_ptr_base.h:976:17: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘std::nullptr_t’
/usr/include/c++/5/bits/shared_ptr_base.h:973:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::auto_ptr<_Up>&&)
  __shared_ptr(std::auto_ptr<_Tp1>&& __r);
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:973:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘std::auto_ptr<_Up>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:961:2: note: candidate: template<class _Tp1, class _Del, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::unique_ptr<_Up, _Ep>&&)
  __shared_ptr(std::unique_ptr<_Tp1, _Del>&& __r)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:961:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:948:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp1, _Lp>&)
  explicit __shared_ptr(const __weak_ptr<_Tp1, _Lp>& __r)
           ^
/usr/include/c++/5/bits/shared_ptr_base.h:948:11: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘const std::__weak_ptr<_Tp>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:940:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp1, _Lp>&&)
  __shared_ptr(__shared_ptr<_Tp1, _Lp>&& __r) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:940:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:932:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp, _Lp>&&) [with _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(__shared_ptr&& __r) noexcept
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:932:7: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘std::__shared_ptr<repowerd::ProximitySensor, (__gnu_cxx::_Lock_policy)2u>&&’
/usr/include/c++/5/bits/shared_ptr_base.h:928:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:928:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:923:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp, _Lp>&) [with _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __shared_ptr&) noexcept = default;
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:923:7: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘const std::__shared_ptr<repowerd::ProximitySensor, (__gnu_cxx::_Lock_policy)2u>&’
/usr/include/c++/5/bits/shared_ptr_base.h:919:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&, _Tp*)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r, _Tp* __p) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:919:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   candidate expects 2 arguments, 1 provided
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:914:9: note: candidate: template<class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter, _Alloc)
         __shared_ptr(nullptr_t __p, _Deleter __d, _Alloc __a)
         ^
/usr/include/c++/5/bits/shared_ptr_base.h:914:9: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::nullptr_t’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:909:2: note: candidate: template<class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter)
  __shared_ptr(nullptr_t __p, _Deleter __d)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:909:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::nullptr_t’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:900:2: note: candidate: template<class _Tp1, class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter, _Alloc)
  __shared_ptr(_Tp1* __p, _Deleter __d, _Alloc __a)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:900:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:891:2: note: candidate: template<class _Tp1, class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter)
  __shared_ptr(_Tp1* __p, _Deleter __d)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:891:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:881:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*)
  explicit __shared_ptr(_Tp1* __p)
           ^
/usr/include/c++/5/bits/shared_ptr_base.h:881:11: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullProximitySensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:876:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr() [with _Tp = repowerd::ProximitySensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       constexpr __shared_ptr() noexcept
                 ^
/usr/include/c++/5/bits/shared_ptr_base.h:876:17: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/5/bits/shared_ptr_base.h: In instantiation of ‘std::__shared_ptr<_Tp, _Lp>& std::__shared_ptr<_Tp, _Lp>::operator=(std::__shared_ptr<_Tp1, _Lp>&&) [with _Tp1 = {anonymous}::NullLightSensor; _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’:
/usr/include/c++/5/bits/shared_ptr.h:302:4:   required from ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp1>&&) [with _Tp1 = {anonymous}::NullLightSensor; _Tp = repowerd::LightSensor]’
/home/ubuntu/repowerd/src/default_daemon_config.cpp:534:18:   required from here
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: error: no matching function for call to ‘std::__shared_ptr<repowerd::LightSensor, (__gnu_cxx::_Lock_policy)2u>::__shared_ptr(std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type)’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:1146:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp, _Lp>&, std::nothrow_t) [with _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __weak_ptr<_Tp, _Lp>& __r, std::nothrow_t)
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:1146:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/5/bits/shared_ptr_base.h:1094:2: note: candidate: template<class _Alloc, class ... _Args> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...)
  __shared_ptr(_Sp_make_shared_tag __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:1094:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::_Sp_make_shared_tag’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:976:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t) [with _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u; std::nullptr_t = std::nullptr_t]
       constexpr __shared_ptr(nullptr_t) noexcept : __shared_ptr() { }
                 ^
/usr/include/c++/5/bits/shared_ptr_base.h:976:17: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘std::nullptr_t’
/usr/include/c++/5/bits/shared_ptr_base.h:973:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::auto_ptr<_Up>&&)
  __shared_ptr(std::auto_ptr<_Tp1>&& __r);
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:973:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘std::auto_ptr<_Up>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:961:2: note: candidate: template<class _Tp1, class _Del, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::unique_ptr<_Up, _Ep>&&)
  __shared_ptr(std::unique_ptr<_Tp1, _Del>&& __r)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:961:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:948:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp1, _Lp>&)
  explicit __shared_ptr(const __weak_ptr<_Tp1, _Lp>& __r)
           ^
/usr/include/c++/5/bits/shared_ptr_base.h:948:11: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ is not derived from ‘const std::__weak_ptr<_Tp>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:940:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp1, _Lp>&&)
  __shared_ptr(__shared_ptr<_Tp1, _Lp>&& __r) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:940:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:932:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp, _Lp>&&) [with _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(__shared_ptr&& __r) noexcept
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:932:7: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘std::__shared_ptr<repowerd::LightSensor, (__gnu_cxx::_Lock_policy)2u>&&’
/usr/include/c++/5/bits/shared_ptr_base.h:928:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:928:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:923:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp, _Lp>&) [with _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __shared_ptr&) noexcept = default;
       ^
/usr/include/c++/5/bits/shared_ptr_base.h:923:7: note:   no known conversion for argument 1 from ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’ to ‘const std::__shared_ptr<repowerd::LightSensor, (__gnu_cxx::_Lock_policy)2u>&’
/usr/include/c++/5/bits/shared_ptr_base.h:919:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&, _Tp*)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r, _Tp* __p) noexcept
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:919:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   candidate expects 2 arguments, 1 provided
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:914:9: note: candidate: template<class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter, _Alloc)
         __shared_ptr(nullptr_t __p, _Deleter __d, _Alloc __a)
         ^
/usr/include/c++/5/bits/shared_ptr_base.h:914:9: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::nullptr_t’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:909:2: note: candidate: template<class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter)
  __shared_ptr(nullptr_t __p, _Deleter __d)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:909:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   cannot convert ‘std::move<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>((* & __r))’ (type ‘std::remove_reference<std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>&>::type {aka std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>}’) to type ‘std::nullptr_t’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:900:2: note: candidate: template<class _Tp1, class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter, _Alloc)
  __shared_ptr(_Tp1* __p, _Deleter __d, _Alloc __a)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:900:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:891:2: note: candidate: template<class _Tp1, class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter)
  __shared_ptr(_Tp1* __p, _Deleter __d)
  ^
/usr/include/c++/5/bits/shared_ptr_base.h:891:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:881:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*)
  explicit __shared_ptr(_Tp1* __p)
           ^
/usr/include/c++/5/bits/shared_ptr_base.h:881:11: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/shared_ptr_base.h:1008:4: note:   mismatched types ‘_Tp1*’ and ‘std::__shared_ptr<{anonymous}::NullLightSensor, (__gnu_cxx::_Lock_policy)2u>’
    __shared_ptr(std::move(__r)).swap(*this);
    ^
/usr/include/c++/5/bits/shared_ptr_base.h:876:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr() [with _Tp = repowerd::LightSensor; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       constexpr __shared_ptr() noexcept
                 ^
/usr/include/c++/5/bits/shared_ptr_base.h:876:17: note:   candidate expects 0 arguments, 1 provided
src/CMakeFiles/repowerd-default-daemon-config.dir/build.make:62: recipe for target 'src/CMakeFiles/repowerd-default-daemon-config.dir/default_daemon_config.cpp.o' failed
make[2]: *** [src/CMakeFiles/repowerd-default-daemon-config.dir/default_daemon_config.cpp.o] Error 1
CMakeFiles/Makefile2:134: recipe for target 'src/CMakeFiles/repowerd-default-daemon-config.dir/all' failed
make[1]: *** [src/CMakeFiles/repowerd-default-daemon-config.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by peat-psuwit** [comment]
Migrated to GitLab.

https://gitlab.com/ubports/core/repowerd/-/merge_requests/18

**Pull request closed without merging**
