### PR TITLE
Actually bring the new repowerd to xenial

### PR DESCRIPTION
**Pull request by peat-psuwit**
As the commit bumping the changelog entry has not been built for xenial yet, this PR offers an opportunity to do so. This PR also fixes a couple of issues that prevent the new repowerd to be used.

This PR comes with Jenkinsfile update.

### CODE REVIEW

**Comment by Flohack74** [comment]
I am bsaically fine with this but why the change to the state machine?

**Comment by peat-psuwit** [comment]
The code from Canonical will make the phone suspend when playing music and turn off the screen with the power button. That's why I made that revert.

Or do you mean something else?

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
No its good, now I got it...

**Review by UniversalSuperBox — APPROVED** [review]
Through tests on all devices I have, this does not seem to affect battery life.

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

If it's about playing music while suspend, then on
Device: FP2
Image: 2020-W36
the music plays while suspended.

**Comment by peat-psuwit** [comment]
That's good enough, thanks.

**Pull request merged**
